# -*- coding: utf-8 -*-
# 关联词题库 · 内容源档（唯一真实来源；data/*.js 由 scripts/build_content.py 生成）
#
# 写法：词与词之间用空格；可被弄错的位置写成 [词#slot]；需要手动指定拼音写成 词/pinyin
# errors: (slot, 错误写法, 偏误类型, 中文说明, English)
#
# 选句规则（Mint 定）：
#   1. 正确句必须是真实生活中会发生的情境，前后逻辑关系本来就存在，不是为了语法硬造。
#   2. 错误句只收学习者真实常犯的关联词偏误，不为了凑错随便换词。
#      PAIR  搭配错误：只要…才、只有…就、虽然…所以、如果…所以、即使…但是、既然…所以
#      LOGIC 语义误用：果然/竟然、而且/但是、不但没…而且（应为反而）、不是…就是（应为而是）
#      FORM  条件句式错误：无论/不管 + 陈述句（应该用「多」「哪」等表示任何情况）
#      TIME  就/才误用：早、快用「就」；晚、慢用「才」
#   3. 近义词互换（但是/可是、所以/因此、仍然/依然、竟然/居然）不算错误，永远不能出题。

TEACHER_BASIC = [
# ---------- 因为……所以 ----------
dict(f="CAUSE", s="[因为#c1] 早上 的 巴士 一直 不 来 ， [所以#c2] 阿明 叫 了 Grab/Grab 去 上班 。",
 e=[("c1","虽然","PAIR","「虽然」要和「但是」搭配；这里巴士不来是叫Grab的原因","虽然 pairs with 但是; here the bus not coming is the reason.")],
 en="Because the morning bus never came, Ah Ming took a Grab to work."),
dict(f="CAUSE", s="[因为#c1] 高速公路 发生 车祸 ， [所以#c2] 爸爸 比 平时 晚 了 一 个 小时 到家 。",
 e=[("c1","虽然","PAIR","「虽然」不能和「所以」搭配","虽然 can't pair with 所以.")],
 en="Because there was an accident on the highway, Dad got home an hour later than usual."),
# ---------- 虽然……但是 / 却 ----------
dict(f="TURN", s="[虽然#c1] 这 摊 榴莲 比较 贵 ， [但是#c2] 每天 都 有 人 排队 。",
 e=[("c2","所以","PAIR","「虽然」要和「但是」搭配，不能接「所以」","虽然 pairs with 但是, not 所以."),
    ("c1","因为","PAIR","「因为」不能和「但是」搭配","因为 can't pair with 但是.")],
 en="Although this durian stall is pricier, there's a queue every day."),
dict(f="TURN", s="[虽然#c1] 他 是 马来西亚人 ， [但是#c2] 从来 没 吃 过 榴莲 。",
 e=[("c2","所以","PAIR","「虽然」要和「但是」搭配；没吃过榴莲是出乎意料，不是结果","虽然 pairs with 但是; never trying durian is unexpected, not a result.")],
 en="Although he's Malaysian, he has never eaten durian."),
dict(f="TURN", s="[虽然#c1] 阿莉 学 了 两 年 华语 ， 看到 汉字 [却#c2] 还是 很 头痛 。",
 e=[("c1","因为","PAIR","「因为」不能和「却」搭配；学了两年还头痛是反差，不是原因","因为 can't pair with 却; it's a contrast, not a cause.")],
 en="Although Ali has studied Mandarin for two years, Chinese characters still give her a headache."),
dict(f="TURN", s="[虽然#c1] 她 说 自己 不 会 唱歌 ， [但是#c2] 唱 起来 很 好听 。",
 e=[("c1","因为","PAIR","「因为」不能和「但是」搭配","因为 can't pair with 但是.")],
 en="Although she said she can't sing, she actually sings beautifully."),
# ---------- 尽管……还是 ----------
dict(f="CONCESSION", s="[尽管#c1] 医生 叫 他 少 吃 甜 的 ， 他 [还是#c2] 每天 喝 奶茶 。",
 e=[("c1","因为","LOGIC","医生的话和他的做法相反，是让步，不是原因","The doctor's advice contrasts with what he does; it's not a reason.")],
 en="Even though the doctor told him to cut down on sweets, he still drinks milk tea every day."),
# ---------- 而且 / 但是（成对教学） ----------
dict(f="MORE", s="这 间 房 租金 便宜/piányi ， [而且#c1] 走路 到 地铁站 只要 五 分钟 。",
 e=[("c1","但是","LOGIC","便宜和离地铁站近都是优点，没有转折，要用「而且」","Both are advantages — no contrast, so use 而且.")],
 en="This room is cheap, and it's only a five-minute walk to the MRT station."),
dict(f="TURN", s="这 间 房 租金 便宜/piányi ， [但是#c1] 离 地铁站 很 远 ， 每天 要 多 花 一 个 小时 。",
 e=[("c1","而且","LOGIC","便宜是优点，离得远是缺点，前后相反，要用「但是」","Cheap is good, far is bad — that's a contrast, so use 但是.")],
 en="This room is cheap, but it's far from the MRT — an extra hour every day."),
# ---------- 不但……而且 ----------
dict(f="MORE_PAIR", s="这 个 补习 老师 [不但#c1] 教 得 清楚 ， [而且#c2] 很 有 耐心 。",
 e=[("c1","虽然","PAIR","两个都是优点，是递进；「虽然」不能和「而且」搭配","Both are strengths; 虽然 can't pair with 而且.")],
 en="This tutor not only explains clearly, but is also very patient."),
dict(f="MORE_PAIR", s="这 家 店 的 椰浆饭 [不但#c1] 便宜/piányi ， [而且#c2] 分量 很 多 。",
 e=[("c1","虽然","PAIR","便宜和分量多都是优点；「虽然」不能和「而且」搭配","Both are good points; 虽然 can't pair with 而且.")],
 en="The nasi lemak here is not only cheap, but the portions are big."),
# ---------- 不但没……反而 ----------
dict(f="OPPOSITE", s="吃 了 药 以后 ， 感冒 不但 没 好 ， [反而#c1] 更 严重 了 。",
 e=[("c1","而且","LOGIC","结果和预期相反，要用「反而」；「而且」只是再加一点","The result goes against expectation, so use 反而; 而且 just adds.")],
 en="After taking the medicine, the cold didn't get better — it actually got worse."),
# ---------- 如果……就 ----------
dict(f="CONDITION", s="[如果#c1] 明天 还 下 大雨 ， [就#c2] 改成 网上 上课 吧 。",
 e=[("c2","所以","PAIR","「如果」是假设，要和「就」搭配，不能接「所以」","如果 is a hypothesis and pairs with 就, not 所以.")],
 en="If it's still pouring tomorrow, let's switch to online class."),
dict(f="CONDITION", s="[如果#c1] 你 下午 有 空/kòng ， [就#c2] 一起 去 看 新 房子 吧 。",
 e=[("c2","所以","PAIR","「如果」要和「就」搭配","如果 pairs with 就.")],
 en="If you're free this afternoon, let's go see the new house together."),
# ---------- 只要……就 ----------
dict(f="SUFFICIENT", s="[只要#c1] 先 在 网上 预约 ， 到 了 诊所 [就#c2] 可以 直接 看 医生 。",
 e=[("c2","才","PAIR","「只要」和「就」搭配；「才」是和「只有」搭配的","只要 pairs with 就; 才 goes with 只有.")],
 en="As long as you book online first, you can see the doctor straight away at the clinic."),
dict(f="SUFFICIENT", s="[只要#c1] 手机 有 网络 ， 你 [就#c2] 可以 用 这 个 App/App 上课 。",
 e=[("c2","才","PAIR","「只要」和「就」搭配，不是「才」","只要 pairs with 就, not 才.")],
 en="As long as your phone has internet, you can take class with this app."),
dict(f="SUFFICIENT", s="[只要#c1] 按 一下 这 个 按钮 ， 门 [就#c2] 会 打开 。",
 e=[("c2","才","PAIR","「只要」和「就」搭配，不是「才」","只要 pairs with 就, not 才.")],
 en="Just press this button and the door will open."),
# ---------- 只有……才 ----------
dict(f="NECESSARY", s="[只有#c1] 交 了 报名费 ， 名字 [才#c2] 会 出现 在 名单 上 。",
 e=[("c2","就","PAIR","「只有」和「才」搭配；「就」是和「只要」搭配的","只有 pairs with 才; 就 goes with 只要.")],
 en="Only after paying the registration fee will your name appear on the list."),
dict(f="NECESSARY", s="[只有#c1] 每天 开口 说 ， 口语 [才#c2] 会 慢慢 流利 起来 。",
 e=[("c2","就","PAIR","「只有」要和「才」搭配","只有 must pair with 才.")],
 en="Only by speaking every day will your spoken Chinese gradually become fluent."),
# ---------- 即使……也 ----------
dict(f="CONCESSION", s="[即使#c1] 这次 考试 没 考好 ， [也#c2] 不要 放弃 。",
 e=[("c2","但是","PAIR","「即使」要和「也」搭配；「即使……但是」是常见错误","即使 pairs with 也; 即使…但是 is a common mistake.")],
 en="Even if you didn't do well in this exam, don't give up."),
dict(f="CONCESSION", s="[即使#c1] 老板 没有 要求 ， [也#c2] 要 把 报告 检查 两 次 。",
 e=[("c2","但是","PAIR","「即使」要和「也」搭配","即使 pairs with 也.")],
 en="Even if the boss doesn't ask for it, you should check the report twice."),
dict(f="CONCESSION", s="[即使#c1] 只有 一 个 学生 来 ， [也#c2] 要 照常 上课 。",
 e=[("c2","但是","PAIR","「即使」要和「也」搭配","即使 pairs with 也.")],
 en="Even if only one student comes, class goes ahead as usual."),
# ---------- 无论 / 不管 + 任何情况 ----------
dict(f="UNRESTRICTED", s="无论 天气 [多#c1] 热 ， 爷爷 都 坚持 每天 早上 散步 。",
 e=[("c1","很","FORM","「无论」后面要说「任何情况」，用「多热」，不能用「很热」","无论 needs \"however hot\" (多热), not a plain statement (很热).")],
 en="No matter how hot it is, Grandpa insists on a walk every morning."),
dict(f="UNRESTRICTED", s="无论 你 选 [哪#c1] 一 天 ， 我 都 有 空/kòng 。",
 e=[("c1","这","FORM","「无论」后面要有选择，用「哪一天」，不能是确定的「这一天」","无论 needs an open choice (哪一天), not a fixed one (这一天).")],
 en="Whichever day you pick, I'm free."),
dict(f="UNRESTRICTED", s="不管 工作 [多#c1] 忙 ， 他 都 会 回家 吃 晚饭 。",
 e=[("c1","很","FORM","「不管」后面要说「任何情况」，用「多忙」","不管 needs \"however busy\" (多忙), not 很忙.")],
 en="However busy work gets, he always comes home for dinner."),
# ---------- 既然……就 ----------
dict(f="CAUSE_DECISION", s="[既然#c1] 你 已经 买 了 票 ， [就#c2] 一起 去 看 吧 。",
 e=[("c2","所以","PAIR","「既然」后面用「就」提出决定，不用「所以」","既然 is followed by 就 for the decision, not 所以.")],
 en="Since you've already bought the tickets, let's go watch it together."),
dict(f="CAUSE_DECISION", s="[既然#c1] 明天 学校 放假 ， 今天 [就#c2] 不用 准备 功课 了 。",
 e=[("c1","虽然","LOGIC","放假是做决定的理由，不是转折","The holiday is the reason for the decision, not a contrast.")],
 en="Since school is off tomorrow, there's no need to prepare homework today."),
# ---------- 果然 / 竟然 ----------
dict(f="EXPECTED", s="天气 预报 说 傍晚 会 下雨 ， 傍晚 [果然#c1] 下 起 了 大雨 。",
 e=[("c1","竟然","LOGIC","预报已经说了，下雨是意料之中，要用「果然」","The forecast predicted it — expected, so 果然.")],
 en="The forecast said it would rain in the evening, and sure enough it poured."),
dict(f="EXPECTED", s="妈妈 说 那 家 店 的 面 很 好吃 ， 我 一 试 ， [果然#c1] 很 好吃 。",
 e=[("c1","竟然","LOGIC","妈妈已经说过，好吃是意料之中","Mum already said so — it's expected.")],
 en="Mum said that shop's noodles are great; I tried them, and sure enough they were."),
dict(f="SURPRISE", s="阿明 平时 很 少 运动 ， 这次 马拉松 [竟然#c1] 跑 完 了 全程 。",
 e=[("c1","果然","LOGIC","平时很少运动，跑完全程是意料之外，要用「竟然」","He rarely exercises — finishing was a surprise, so 竟然.")],
 en="Ah Ming rarely exercises, yet he actually finished the whole marathon."),
dict(f="SURPRISE", s="我 只是 随便 买 了 一 张 彩票 ， [竟然#c1] 中/zhòng 了 奖 。",
 e=[("c1","果然","LOGIC","随便买的，中奖是意料之外","A random ticket winning is unexpected.")],
 en="I just bought a lottery ticket on a whim, and I actually won."),
# ---------- 就 / 才（时间早晚） ----------
dict(f="TIME", s="阿莉 平常 七 点 就 到 公司 ， 今天 九 点 [才#c1] 到 。",
 e=[("c1","就","TIME","九点比平常晚，晚要用「才」","Nine is later than usual — late takes 才.")],
 en="Ali usually gets to the office at seven, but today she only arrived at nine."),
dict(f="TIME", s="这 份 报告 他 一 个 小时 [就#c1] 写 完 了 ， 大家 都 很 惊讶 。",
 e=[("c1","才","TIME","一个小时就写完是很快，快要用「就」","Finishing in an hour is fast — fast takes 就.")],
 en="He finished this report in just an hour; everyone was amazed."),
# ---------- 不是……而是 ----------
dict(f="CORRECTION", s="我 迟到 不是 因为 睡过头 ， [而是#c1] 因为 地铁 故障 。",
 e=[("c1","就是","LOGIC","「不是……就是……」表示二选一；这里是更正原因，要用「而是」","不是…就是… means either/or; to correct the reason use 而是.")],
 en="I was late not because I overslept, but because the MRT broke down."),
]

# DETECTIVE 短文暂不录音（阅读模式，没有录音也能玩）。以下三篇待 Mint 按同样标准审核后再扩充。
DETECTIVE_BASIC = [
dict(title="下雨 的 星期六",
 s="星期六 下午 ， 小丽 约 了 朋友 去 夜市 。 [因为#s1] 突然 下起 大雨 ， [所以#s2] 她们 先 在 咖啡店 等 雨 停 。 [虽然#s3] 等 了 半 个 小时 ， [但是#s4] 雨 一直 没有 变小 。 她们 只好 改 去 附近 的 商场 吃 晚餐 。",
 slots=dict(
  s1=[("虽然","PAIR","「虽然」不能和「所以」搭配","虽然 can't pair with 所以.")],
  s2=[("但是","PAIR","「因为」不能和「但是」搭配","因为 can't pair with 但是.")],
  s3=[("因为","PAIR","「因为」不能和「但是」搭配","因为 can't pair with 但是.")],
  s4=[("所以","PAIR","「虽然」要和「但是」搭配","虽然 pairs with 但是.")]),
 en="On Saturday afternoon Xiaoli arranged to go to the night market with a friend. Because heavy rain suddenly started, they first waited in a café. Although they waited half an hour, the rain didn't ease, so they went to a nearby mall for dinner instead.",
 q=("她们 最后 为什么 没有 去 夜市 ？","Why didn't they go to the night market in the end?",
    ["雨 一直 没有 变小","夜市 没有 开","小丽 不 想 见 朋友"])),
dict(title="光华 的 第一次 面试",
 s="光华 下个月 有 一 个 面试 。 [只要#s1] 有 空/kòng ， 他 [就#s2] 对着 镜子 练习 自我介绍 。 面试 那天 路上 很 塞车 ， [但是#s3] 他 提早 出门 ， 还是 准时 到 了 。 面试官 [不但#s4] 问 了 他 的 经验 ， [而且#s5] 请 他 用 华语 介绍 自己 。",
 slots=dict(
  s1=[("只有","PAIR","「只有」要和「才」搭配","只有 pairs with 才.")],
  s2=[("才","PAIR","「只要」要和「就」搭配","只要 pairs with 就.")],
  s3=[("而且","LOGIC","塞车是阻碍，提早出门是应对，前后是转折","Traffic is an obstacle; leaving early counters it — a contrast.")],
  s4=[("虽然","PAIR","「虽然」不能和「而且」搭配","虽然 can't pair with 而且.")],
  s5=[("但是","LOGIC","两个都是面试官的要求，是递进，不是转折","Both are the interviewer's requests — they add up, no contrast.")]),
 en="Guanghua has an interview next month. Whenever he has time, he practises his self-introduction in the mirror. On the day, traffic was bad, but he left early and still arrived on time. The interviewer not only asked about his experience, but also asked him to introduce himself in Mandarin.",
 q=("光华 为什么 能 准时 到 ？","Why did Guanghua arrive on time?",
    ["他 提早 出门","路上 不 塞车","面试 延迟 了"])),
dict(title="新年 前 的 超市",
 s="农历新年 快 到 了 ， 超市 里 人 特别 多 。 家豪 想 买 年饼 ， [可是#s1] 他 最 喜欢 的 那种 已经 卖完 了 。 [既然#s2] 买 不 到 ， 他 [就#s3] 决定 回家 自己 做 。 [虽然#s4] 第一次 做 得 不 太 好看 ， 家人 [却#s5] 都 说 很 好吃 。",
 slots=dict(
  s1=[("而且","LOGIC","想买和卖完了是冲突，要用转折","Wanting it vs. sold out is a conflict — use a contrast word.")],
  s2=[("虽然","LOGIC","买不到是做决定的理由，不是让步","Not finding them is the reason for his decision.")],
  s3=[("所以","PAIR","「既然」后面用「就」提出决定","既然 is followed by 就.")],
  s4=[("因为","LOGIC","不好看和好吃是反差，不是原因","Not pretty vs. tasty is a contrast, not a cause.")],
  s5=[("所以","PAIR","「虽然」不能和「所以」搭配","虽然 can't pair with 所以.")]),
 en="Chinese New Year is coming and the supermarket is packed. Jiahao wanted to buy New Year cookies, but his favourite kind was sold out. Since he couldn't buy them, he decided to make them at home. Although his first batch didn't look great, his family all said they were delicious.",
 q=("家豪 为什么 自己 做 年饼 ？","Why did Jiahao make the cookies himself?",
    ["他 喜欢 的 那种 卖完 了","超市 没有 开","家人 叫 他 做"])),
dict(title="巴刹 买 菜",
 s="星期天 早上 ， 妈妈 带 小美 去 巴刹 买 菜 。 [因为#s1] 去 得 太 晚 ， [所以#s2] 新鲜 的 鱼 已经 卖完 了 。 [虽然#s3] 没 买 到 鱼 ， [但是#s4] 她们 买 到 了 很 便宜/piányi 的 青菜 。 妈妈 说 ： 「 [只要#s5] 早 一点 出门 ， 下次 [就#s6] 买 得 到 。 」",
 slots=dict(
  s1=[("虽然","PAIR","「虽然」不能和「所以」搭配；去得晚是卖完的原因","虽然 can't pair with 所以; going late is the reason.")],
  s2=[("但是","PAIR","「因为」不能和「但是」搭配","因为 can't pair with 但是.")],
  s3=[("因为","PAIR","「因为」不能和「但是」搭配；没买到鱼和买到青菜是转折","因为 can't pair with 但是; it's a contrast.")],
  s4=[("所以","PAIR","「虽然」要和「但是」搭配","虽然 pairs with 但是.")],
  s5=[("只有","PAIR","「只有」要和「才」搭配；这里是「只要……就……」","只有 pairs with 才; here it's 只要…就….")],
  s6=[("才","PAIR","「只要」要和「就」搭配","只要 pairs with 就.")]),
 en="On Sunday morning Mum took Xiaomei to the wet market. Because they went too late, the fresh fish was sold out. Although they didn't get fish, they bought very cheap vegetables. Mum said: 'As long as we leave a bit earlier, next time we'll get some.'",
 q=("她们 为什么 没 买 到 鱼 ？","Why didn't they get any fish?",
    ["去 得 太 晚 了","鱼 太 贵 了","妈妈 不 喜欢 吃 鱼"])),
dict(title="开斋节 的 邀请",
 s="开斋节 那天 ， 同事 阿曼 请 伟杰 去 他 家 吃 饭 。 伟杰 本来 有点 担心 ， [因为#s1] 他 不 太 会 说 马来语 。 没想到 阿曼 的 家人 [不但#s2] 很 热情 ， [而且#s3] 一直 请 他 多 吃 一点 。 [既然#s4] 大家 这么 欢迎 他 ， 他 [就#s5] 决定 明年 也 要 来 。",
 slots=dict(
  s1=[("虽然","LOGIC","不太会说马来语是担心的原因，不是让步","Not speaking Malay well is the reason for worrying.")],
  s2=[("虽然","PAIR","「虽然」不能和「而且」搭配；热情和请他多吃都是好的，是递进","虽然 can't pair with 而且; both points are positive and add up.")],
  s3=[("但是","LOGIC","热情和请他多吃是同方向的，不是转折","Both points go the same way — no contrast.")],
  s4=[("虽然","LOGIC","大家欢迎他是做决定的理由，不是转折","Being welcomed is the reason for his decision.")],
  s5=[("但是","PAIR","「既然」后面用「就」提出决定","既然 is followed by 就 for the decision.")]),
 en="On Hari Raya, his colleague Aiman invited Weijie home for a meal. Weijie was a bit worried at first, because he doesn't speak much Malay. Unexpectedly, Aiman's family was not only very warm but kept asking him to eat more. Since everyone welcomed him so much, he decided to come again next year.",
 q=("伟杰 一开始 为什么 担心 ？","Why was Weijie worried at first?",
    ["他 不 太 会 说 马来语","他 不 喜欢 吃 饭","阿曼 的 家 太 远"])),
dict(title="手机 没 电",
 s="佩玲 在 商场 等 朋友 。 突然 手机 响 了 一下 ， 电量 只 剩 百分之五 。 [如果#s1] 手机 没 电 ， 她 [就#s2] 联络 不 到 朋友 了 。 [于是#s3] 她 走进 附近 的 嘛嘛档 ， 点 了 一 杯 拉茶 ， 顺便 用 那里 的 插座 充电 。 [虽然#s4] 只 充 了 十 分钟 ， 电量 [却#s5] 已经 够 用 了 。",
 slots=dict(
  s1=[("虽然","LOGIC","手机还没没电，这里是假设","The phone isn't dead yet — this is a condition.")],
  s2=[("但是","PAIR","「如果」要和「就」搭配","如果 pairs with 就.")],
  s3=[("虽然","POSITION","「虽然」放在这里句子没有说完，这里要接下一步的行动","With 虽然 here the sentence is unfinished; we need the next action.")],
  s4=[("因为","PAIR","「因为」不能和「却」搭配；只充十分钟和够用是反差","因为 can't pair with 却; it's a contrast.")],
  s5=[("所以","LOGIC","只充十分钟却够用，是出乎意料，不是结果","Being enough after ten minutes is surprising, not a result.")]),
 en="Peiling was waiting for a friend at the mall. Suddenly her phone beeped — only 5% battery left. If her phone died, she wouldn't be able to reach her friend. So she went into a nearby mamak stall, ordered a teh tarik, and charged her phone at a socket there. Although she only charged for ten minutes, it was already enough.",
 q=("佩玲 为什么 走进 嘛嘛档 ？","Why did Peiling go into the mamak stall?",
    ["用 那里 的 插座 充电","去 找 朋友","去 买 新 手机"])),
dict(title="学校 运动会",
 s="下个星期 有 运动会 ， 子轩 报名 了 四百 米 赛跑 。 他 每天 放学 后 [先#s1] 做 功课 ， [再#s2] 去 操场 练习 。 即使 下雨 ， 他 [也#s4] 在 走廊 跑步 。 比赛 那天 ， 大家 都 以为 他 会 很 紧张 ， 他 [竟然#s5] 跑 了 第二名 。",
 slots=dict(
  s1=[("虽然","LOGIC","这里是先后顺序，不是让步","This is an order of steps, not a concession.")],
  s2=[("所以","LOGIC","去练习是下一步，不是做功课的结果","Practising is the next step, not a result.")],
  s4=[("但是","PAIR","「即使」要和「也」搭配；「即使……但是」是常见错误","即使 pairs with 也; 即使…但是 is a common mistake.")],
  s5=[("果然","LOGIC","大家以为他会紧张，他跑第二名是意料之外","Everyone expected him to be nervous — second place was a surprise.")]),
 en="There's a sports day next week, and Zixuan signed up for the 400 m race. Every day after school he does his homework first, then practises on the field. Even if it rains, he runs in the corridor. On race day everyone thought he would be nervous, but he actually came second.",
 q=("下雨 的 时候 ， 子轩 怎么 练习 ？","How does Zixuan practise when it rains?",
    ["在 走廊 跑步","在 家 休息","去 游泳"])),
dict(title="图书馆 的 书",
 s="俊宏 在 图书馆 借 了 一 本 书 ， 两 个 星期 后 要 还 。 [可是#s1] 他 一直 忘 了 ， 等 到 想起来 ， 已经 过期 三 天 了 。 [只有#s2] 交 了 罚款 ， 他 [才#s3] 可以 再 借 书 。 [虽然#s4] 罚款 不 多 ， 他 [还是#s5] 觉得 很 可惜 。",
 slots=dict(
  s1=[("所以","LOGIC","要还书和一直忘了是冲突，不是因果","Needing to return it and forgetting conflict — it's not cause and effect.")],
  s2=[("只要","PAIR","后面是「才」，要用「只有」","With 才 later, the first word must be 只有.")],
  s3=[("就","PAIR","「只有」要和「才」搭配","只有 pairs with 才.")],
  s4=[("因为","LOGIC","罚款不多和觉得可惜是反差，不是原因","A small fine and still feeling bad is a contrast, not a cause.")],
  s5=[("所以","LOGIC","觉得可惜不是罚款不多的结果","Feeling bad isn't a result of the fine being small.")]),
 en="Junhong borrowed a book from the library and had to return it in two weeks. But he kept forgetting, and by the time he remembered, it was three days overdue. Only after paying the fine can he borrow books again. Although the fine is small, he still feels it was a waste.",
 q=("俊宏 为什么 要 交 罚款 ？","Why does Junhong have to pay a fine?",
    ["书 过期 了 才 还","他 把 书 弄 坏 了","他 借 了 太 多 书"])),
dict(title="家里 的 猫",
 s="诗琪 家 的 猫 叫 小黑 。 [一#s1] 听到 开 罐头 的 声音 ， 它 [就#s2] 跑 到 厨房 。 [无论#s3] 诗琪 [怎么#s4] 叫 它 ， 它 [都#s5] 不 理 ， [除非#s6] 手上 有 吃 的 ， [否则#s7] 它 一直 睡觉 。",
 slots=dict(
  s1=[("虽然","LOGIC","听到声音马上跑去，是一发生就接着发生","It runs over as soon as it hears the sound.")],
  s2=[("才","PAIR","「一……就……」表示马上发生，不用「才」","一…就… means right away; not 才.")],
  s3=[("因为","LOGIC","「怎么叫」表示任何叫法，要用「无论」","怎么叫 means however she calls, so use 无论.")],
  s4=[("这样","FORM","「无论」后面要有任何情况，用「怎么」，不能用确定的「这样」","无论 needs an open case (怎么), not a fixed one (这样).")],
  s5=[("就","PAIR","「无论」要和「都」搭配","无论 pairs with 都.")],
  s6=[("如果","LOGIC","后面有「否则」，前面要用「除非」表示唯一的例外","With 否则 later, use 除非 for the only exception.")],
  s7=[("所以","PAIR","「除非」要和「否则」搭配","除非 pairs with 否则.")]),
 en="Shiqi's cat is called Xiaohei. As soon as it hears a can being opened, it runs to the kitchen. However Shiqi calls it, it ignores her — unless she has food in her hand, it just keeps sleeping.",
 q=("小黑 什么 时候 会 跑 到 厨房 ？","When does Xiaohei run to the kitchen?",
    ["听到 开 罐头 的 声音","诗琪 叫 它 的 时候","想 睡觉 的 时候"])),
dict(title="新 同学",
 s="班上 来 了 一 位 新 同学 ， 叫 美美 。 她 刚 从 槟城 搬 来 ， [所以#s1] 一个 朋友 也 没有 。 下课 时 ， 拉吉 主动 请 她 一起 吃 东西 。 美美 [不但#s2] 说 了 谢谢 ， [还#s3] 教 大家 说 几 句 福建话 。 没想到 大家 都 笑 了 ， 教室 [反而#s4] 比 平时 更 热闹 。",
 slots=dict(
  s1=[("但是","LOGIC","刚搬来是没有朋友的原因，不是转折","Having just moved is why she has no friends.")],
  s2=[("虽然","PAIR","「虽然」不能和「还」这样搭配；这里是递进","虽然 can't pair with 还 here; this adds more.")],
  s3=[("但是","PAIR","「不但」后面要递进，不是转折","不但 needs an adding word, not a contrast.")],
  s4=[("所以","LOGIC","来了新同学，本来以为会安静，结果更热闹，是相反方向，用「反而」","A new student could make class quieter — livelier is the opposite, so 反而.")]),
 en="A new classmate called Meimei joined the class. She had just moved from Penang, so she didn't have any friends. At break, Raji invited her to eat together. Meimei not only said thank you, but also taught everyone some Hokkien. To everyone's surprise, they all laughed, and the class was even livelier than usual.",
 q=("美美 为什么 没有 朋友 ？","Why doesn't Meimei have any friends?",
    ["她 刚 从 槟城 搬 来","她 不 喜欢 说话","她 常常 请假"])),
dict(title="榴莲 季",
 s="榴莲 季 到 了 ， 爸爸 开车 带 全家 去 文冬 吃 榴莲 。 路上 很 塞车 ， 他们 本来 以为 会 很 晚 到 ， 结果 只 迟 了 半 个 小时 。 那里 的 榴莲 [既#s1] 便宜/piányi [又#s2] 好吃 。 [与其#s3] 在 城市 买 贵 的 ， [不如#s4] 每年 来 这里 吃 。",
 slots=dict(
  s1=[("虽然","LOGIC","便宜和好吃是同时成立的两个优点，不是让步","Cheap and tasty are two qualities together, not a concession.")],
  s2=[("但","LOGIC","便宜和好吃都是优点，没有转折","Both are good points — no contrast.")],
  s3=[("因为","LOGIC","这里是比较两种做法，不是原因","This compares two choices; it's not a reason.")],
  s4=[("所以","PAIR","「与其」要和「不如」搭配，表示选后面","与其 pairs with 不如 to prefer the second option.")]),
 en="Durian season is here, and Dad drove the family to Bentong to eat durian. Traffic was heavy; they thought they'd arrive very late, but in the end they were only half an hour late. The durians there are both cheap and tasty. Rather than buying expensive ones in the city, it's better to come here every year.",
 q=("爸爸 觉得 为什么 每年 都 应该 来 文冬 ？","Why does Dad think they should come to Bentong every year?",
    ["那里 的 榴莲 便宜 又 好吃","那里 不 塞车","那里 有 亲戚"])),
dict(title="补习班 换 时间",
 s="补习 老师 发 了 信息 ： 「 [因为#s1] 星期三 是 公共假期 ， 这 个 星期 的 课 改到 星期四 。 」 慧敏 星期四 本来 要 学 钢琴 ， [但是#s2] 钢琴 老师 同意 让 她 改 时间 。 [只要#s3] 提前 一 天 说 ， 老师 [就#s4] 可以 帮 她 调 课 。",
 slots=dict(
  s1=[("虽然","LOGIC","公共假期是改时间的原因，不是让步","The public holiday is the reason for the change.")],
  s2=[("因为","LOGIC","老师同意改时间不是她本来要学钢琴的原因；前后是转折","The teacher agreeing isn't the reason she had piano; it's a contrast.")],
  s3=[("只有","PAIR","后面是「就」，要用「只要」","With 就 later, use 只要.")],
  s4=[("才","PAIR","「只要」要和「就」搭配","只要 pairs with 就.")]),
 en="The tuition teacher sent a message: 'Because Wednesday is a public holiday, this week's class moves to Thursday.' Huimin originally had piano on Thursday, but her piano teacher agreed to change the time. As long as she tells her one day ahead, the teacher can reschedule.",
 q=("补习课 为什么 改到 星期四 ？","Why was tuition moved to Thursday?",
    ["星期三 是 公共假期","补习 老师 生病 了","慧敏 要 学 钢琴"])),
dict(title="搭 轻快铁",
 s="家伟 第一次 自己 搭 轻快铁 去 市中心 。 他 [先#s1] 在 手机 上 查 好 路线 ， [然后#s2] 才 出门 。 [虽然#s3] 中途 要 换 一次 车 ， 他 [却#s4] 一点 也 不 紧张 。 [果然#s5] ， 照着 路线 走 ， 他 准时 到 了 。",
 slots=dict(
  s1=[("虽然","LOGIC","这里是先后步骤，不是让步","These are steps in order, not a concession.")],
  s2=[("所以","LOGIC","出门是下一步，不是查路线的结果","Going out is the next step, not a result.")],
  s3=[("因为","PAIR","「因为」不能和「却」搭配；要换车和不紧张是反差","因为 can't pair with 却; it's a contrast.")],
  s4=[("所以","LOGIC","要换车却不紧张是反差，不是结果","Changing trains but not being nervous is a contrast.")],
  s5=[("竟然","LOGIC","他已经查好路线，准时到是意料之中","He planned the route — arriving on time was expected.")]),
 en="Jiawei took the LRT into the city by himself for the first time. He first checked the route on his phone, and then went out. Although he had to change trains once, he wasn't nervous at all. Sure enough, by following the route he arrived on time.",
 q=("家伟 出门 前 做 了 什么 ？","What did Jiawei do before going out?",
    ["在 手机 上 查 好 路线","打电话 问 朋友","买 了 新 手机"])),
dict(title="生日 蛋糕",
 s="今天 是 妈妈 的 生日 ， 晓晴 想 自己 做 蛋糕 。 [可是#s1] 家里 没有 烤箱 。 [既然#s2] 不能 烤 ， 她 [就#s3] 做 了 一个 不用 烤 的 冰 蛋糕 。 [虽然#s4] 蛋糕 有点 歪 ， 妈妈 [还是#s5] 开心 得 说不出话 。",
 slots=dict(
  s1=[("所以","LOGIC","想做蛋糕和没有烤箱是冲突，不是因果","Wanting to bake and having no oven conflict.")],
  s2=[("虽然","LOGIC","不能烤是做决定的理由，不是让步","Not being able to bake is the reason for her decision.")],
  s3=[("但是","PAIR","「既然」后面用「就」提出决定","既然 is followed by 就 for the decision.")],
  s4=[("因为","LOGIC","蛋糕歪和妈妈开心是反差，不是原因","A lopsided cake and Mum being happy is a contrast.")],
  s5=[("所以","LOGIC","开心不是蛋糕歪的结果","Being happy isn't a result of the cake being lopsided.")]),
 en="Today is Mum's birthday, and Xiaoqing wanted to make a cake herself. But there's no oven at home. Since she couldn't bake, she made a no-bake chilled cake. Although the cake was a bit lopsided, Mum was still so happy she couldn't speak.",
 q=("晓晴 为什么 做 冰 蛋糕 ？","Why did Xiaoqing make a chilled cake?",
    ["家里 没有 烤箱","妈妈 喜欢 冰 的","冰 蛋糕 比较 便宜"])),
dict(title="雨 天 的 巴士",
 s="雨 下 得 很 大 ， 巴士站 挤 满 了 人 。 巴士 [一#s1] 到 ， 大家 [就#s2] 挤 上 车 。 国强 [宁愿#s3] 等 下 一 班 ， [也不#s4] 想 在 车 上 被 挤 。 结果 下 一 班 只要 五 分钟 就 来 了 ， 车 上 [反而#s5] 有 很 多 空位 。",
 slots=dict(
  s1=[("虽然","LOGIC","巴士一到大家马上挤上车，是一发生就接着发生","As soon as the bus arrived, everyone squeezed on.")],
  s2=[("才","PAIR","「一」要和「就」搭配","一 pairs with 就.")],
  s3=[("因为","LOGIC","这里是二选一，宁可选前面","This is choosing between two options, preferring the first.")],
  s4=[("所以不","PAIR","「宁愿」要和「也不」搭配","宁愿 pairs with 也不.")],
  s5=[("而且","LOGIC","本来以为下一班也会很挤，结果很空，是相反方向，用「反而」","He might expect the next bus to be full — empty is the opposite, so 反而.")]),
 en="It was pouring, and the bus stop was packed. As soon as the bus arrived, everyone squeezed on. Guoqiang would rather wait for the next one than be squashed on the bus. In the end the next bus came in only five minutes, and it actually had lots of empty seats.",
 q=("国强 为什么 不 上 第一 班 巴士 ？","Why didn't Guoqiang take the first bus?",
    ["他 不 想 在 车 上 被 挤","他 没有 带 钱","巴士 不 停 站"])),
]
